name: Build
on:
  push:
    branches-ignore:
      - data
      - gh-pages
    tags:
      - '**'
  pull_request:
    branches-ignore:
      - data
      - gh-pages

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev

      - name: Install Buildozer dependencies
        run: |
          pip install --upgrade pip
          pip install --user buildozer cython

      - name: Install AIDL
        run: |
          sudo apt-get update
          sudo apt-get install -y aidl

      - name: Build with Buildozer
        run: |
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./bin/*.apk

      - name: Checkout data branch
        uses: actions/checkout@v2
        with:
          path: data
          ref: data # Branch name

      - name: Push binary to data branch
        if: github.event_name == 'push'
        run: python master/.ci/move_binary.py ./bin/*.apk master data bin

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for cleanup
        uses: actions/checkout@v2

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER /home/runner/work/MusicPlayer/MusicPlayer
          git config --global --add safe.directory /home/runner/work/MusicPlayer/MusicPlayer
          git config --global --unset http.https://github.com/.extraheader
